

export namespace Enums {
  // PAGE_TYPE
  export enum PAGE_TYPE {
    PORTFOLIO_LIST = 'PORTFOLIO_LIST',
    WATCHLIST_LIST = 'WATCHLIST_LIST',
    WATCHLIST_DETAILS = 'WATCHLIST_DETAILS',
    PORTFOLIO_DETAILS = 'PORTFOLIO_DETAILS',
    STOCK_DETAILS = 'STOCK_DETAILS',
    STOCK_SNAPSHOT_DETAILS = 'STOCK_SNAPSHOT_DETAILS',
    DELETE_PORTFOLIO = 'DELETE_PORTFOLIO',
    CREATE_PORTFOLIO = 'CREATE_PORTFOLIO',
    DELETE_WATCHLIST = 'DELETE_WATCHLIST',
    CREATE_WATCHLIST = 'CREATE_WATCHLIST',
    NEW_STOCK_SNAPSHOT_COMMENT = 'NEW_STOCK_SNAPSHOT_COMMENT',
    INTERNAL_STOCK_SEARCH = 'INTERNAL_STOCK_SEARCH',
    EXTERNAL_STOCK_SEARCH = 'EXTERNAL_STOCK_SEARCH',
    EXTERNAL_STOCK_SEARCH_SUCCESS_MODAL = 'EXTERNAL_STOCK_SEARCH_SUCCESS_MODAL',
    EXTERNAL_STOCK_SEARCH_ALREADY_EXISTS = 'EXTERNAL_STOCK_SEARCH_ALREADY_EXISTS'
  };

  // export const PAGE_TYPE = {
  //   PORTFOLIO_LIST: 'PORTFOLIO_LIST',
  //   WATCHLIST_LIST: 'WATCHLIST_LIST',
  //   WATCHLIST_DETAILS: 'WATCHLIST_DETAILS',
  //   PORTFOLIO_DETAILS: 'PORTFOLIO_DETAILS',
  //   STOCK_DETAILS: 'STOCK_DETAILS',
  //   STOCK_SNAPSHOT_DETAILS: 'STOCK_SNAPSHOT_DETAILS',
  //   DELETE_PORTFOLIO: 'DELETE_PORTFOLIO',
  //   CREATE_PORTFOLIO: 'CREATE_PORTFOLIO',
  //   DELETE_WATCHLIST: 'DELETE_WATCHLIST',
  //   CREATE_WATCHLIST: 'CREATE_WATCHLIST',
  //   NEW_STOCK_SNAPSHOT_COMMENT: 'NEW_STOCK_SNAPSHOT_COMMENT'
  // };

  export enum DATA_TABLE_TYPE {
    SINGLE_AXIS,
    DOUBLE_AXIS
  }

  // DATA_TABLE_COLUMN_TYPE
  export enum DATA_TABLE_FIELD_TYPE {
    TEXT,
    BUTTON
  }

  export enum DATA_TABLE_CELL_TYPE {
    HEADER,
    DATA
  }

  export enum DATA_FORMAT_TYPE {
    TEXT,
    DATE,
    NUMBER,
    DOLLAR,
    PERCENT
  }

  export enum NUMBER_FORMATS {
    NONE,
    THOUSANDS,
    MILLIONS,
    BILLIONS
  }

  export enum TEXT_SIZE {
    SMALL,
    MEDIUM,
    LARGE,
    XLARGE
  }

  export enum SYNTHETIC_EVENTS {
    WATCHLIST_UPDATE = 'WATCHLIST_UPDATE',
    WATCHLIST_STOCK_INSERT = 'WATCHLIST_STOCK_INSERT',
    WATCHLIST_STOCK_DELETE = 'WATCHLIST_STOCK_DELETE',
    PORTFOLIO_UPDATE = 'PORTFOLIO_UPDATE',
    PORTFOLIO_TRANSACTION_INSERT = 'PORTFOLIO_TRANSACTION_INSERT',
    PORTFOLIO_TRANSACTION_DELETE = 'PORTFOLIO_TRANSACTION_DELETE',
    STOCK_SNAPSHOT_INSERT = 'STOCK_SNAPSHOT_INSERT',
    STOCK_SNAPSHOT_UPDATE = 'STOCK_SNAPSHOT_UPDATE',
    STOCK_SNAPSHOT_DELETE = 'STOCK_SNAPSHOT_DELETE',
    STOCK_SNAPSHOT_COMMENT_UPDATE = 'STOCK_SNAPSHOT_COMMENT_UPDATE',
    STOCK_SNAPSHOT_COMMENT_DELETE = 'STOCK_SNAPSHOT_COMMENT_DELETE',
    HIDE_NEW_SNAPSHOT_COMMENT = 'HIDE_NEW_SNAPSHOT_COMMENT',
    SHOW_WATCHLIST_DELETE_MODAL = 'SHOW_WATCHLIST_DELETE_MODAL',
    SHOW_WATCHLIST_CREATE_MODAL = 'SHOW_WATCHLIST_CREATE_MODAL',
    SHOW_PORTFOLIO_DELETE_MODAL = 'SHOW_PORTFOLIO_DELETE_MODAL',
    SHOW_PORTFOLIO_CREATE_MODAL = 'SHOW_PORTFOLIO_CREATE_MODAL',
    SHOW_STOCK_DETAILS_MODAL = 'SHOW_STOCK_DETAILS_MODAL',
    SHOW_STOCK_SNAPSHOT_DETAILS_MODAL = 'SHOW_STOCK_SNAPSHOT_DETAILS_MODAL',
    SHOW_INTERNAL_STOCK_SEARCH_MODAL = 'SHOW_INTERNAL_STOCK_SEARCH_MODAL',
    CLEAR_EXTERNAL_STOCK_SEARCH_RESULTS = 'CLEAR_EXTERNAL_STOCK_SEARCH_RESULTS',
    SHOW_EXTERNAL_STOCK_SEARCH_ADD_MODAL = 'SHOW_EXTERNAL_STOCK_SEARCH_ADD_MODAL',
    SHOW_EXTERNAL_STOCK_SEARCH_ALREADY_EXISTS_MODAL = 'SHOW_EXTERNAL_STOCK_SEARCH_ALREADY_EXISTS_MODAL'
  };

  export const HTTP_CALL_TYPE = {
    GET: 'GET',
    POST: 'POST',
    PUT: 'PUT',
    DELETE: 'DELETE'
  }

  export enum APP_ASSET_TYPE {
    WATCHLIST,
    PORTFOLIO,
    STOCK,
    SNAPSHOT,
    COMMENT,
    TRANSACTION
  }
}
